### ISSUE TITLE
hỏi

### ISSUE THREAD

**Issue by trangnth** [locvx1234/Telnet-#1]
1. t lấy windowns (8) làm server mà sao không được
2. sao win 8 có chức năng telnet server mà sao win 10 của t ko có :3 
3. chạy lệnh nó hiện " 'telnet' is not recognized as an internal or external command,
operable program or batch file."
Đã bật mấy cái telnet client vs telnet server rồi

**Comment by trangnth** [comment]
a cái 1, 3 thì được rồi, cơ mà vẫn không telnet  được :3
Could not open connection to the host, on port 23: Connect failed

**Comment by locvx1234** [comment]
1. lỗi đó có thể là do firewall trên server chưa cho phép qua cổng 23 
2. Cái Telnet Server trong Win 10, MS gỡ bỏ rồi

**Comment by trangnth** [comment]
thế cái firewall đấy phải làm thế nào, mà sao MS gỡ cái đấy đi làm gì, nó gây hại gì à

**Comment by locvx1234** [comment]
có thể là cái telnet đó bảo mật kém nên bỏ thôi.

**Comment by locvx1234** [comment]
còn về fw thì tìm hiểu cách "open port windows firewall" và có thể còn phải tắt tạm thời antivirus software đi

**Comment by trangnth** [comment]
ờ để t thử
